apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: apache
  name: apache-controller
spec:
  replicas: 2
  selector:
    name: apache
  template:
    metadata:
      labels:
        name: apache
    spec:
      containers:
      - image: muneeb/apache-flask
        command: ['/bin/sh', '-c']
        args: ['sudo /usr/sbin/apache2ctl -D FOREGROUND']
        name: apache
        ports:
        - containerPort: 80
          name: http-server