apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: asr
  name: asr-controller
spec:
  replicas: 1
  selector:
    name: asr
  template:
    metadata:
      labels:
        name: asr
    spec:
      containers:
      - image: ybga/lucida-dev
        command: ['/bin/sh', '-c']
        args: ['cd speechrecognition/kaldi_gstreamer_asr/ && export GST_PLUGIN_PATH=$LUCIDAROOT/speechrecognition/kaldi_gstreamer_asr/kaldi/tools/gst-kaldi-nnet2-online/src && python kaldigstserver/worker.py -u ws://$WEB_PORT_3000_TCP_ADDR:8888/worker/ws/speech -c sample_english_nnet2.yaml']
        name: asr
        ports:
        - containerPort: 8081
          name: http-server
