apiVersion: v1
kind: Service
metadata:
  name: asr
  labels:
    name: asr
spec:
  type: NodePort
  ports:
    - nodePort: 30002
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: asr
