apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: asrmaster
  name: asr-controller
spec:
  replicas: 1
  selector:
    name: asrmaster
  template:
    metadata:
      labels:
        name: asrmaster
    spec:
      containers:
      - image: ybga/lucida-dev
        command: ['/bin/sh', '-c']
        args: ['export DOCKER=True && cd commandcenter/ && python app.py']
        name: asrmaster
        ports:
        - containerPort: 8081
          name: http-server
