apiVersion: v1
kind: Service
metadata:
  name: asrmaster
  labels:
    name: asrmaster
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    name: asrmaster
