apiVersion: v1
kind: Service
metadata:
  name: dbpedia
  labels:
    name: dbpedia
spec:
  type: LoadBalancer
  ports:
    - port: 3037
      targetPort: 3037
      protocol: TCP
  selector:
    name: dbpedia
