apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dbpedia
  name: dbpedia-controller
spec:
  replicas: 1
  selector:
    name: dbpedia
  template:
    metadata:
      labels:
        name: dbpedia
    spec:
      containers:
      - image: ybga/fuseki
        command: ['/bin/sh', '-c']
        args: ['./fuseki-server --port 3037 --loc db /dbpedia']
        name: dbpedia
        ports:
        - containerPort: 3037
          name: dbpedia
        volumeMounts:
          - mountPath: /jena-fuseki/db/
            name: dbpedia-persistent-storage
            readOnly: false
      volumes:
        - hostPath:
            path: /home/yba/data/db/
          name: dbpedia-persistent-storage
