apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dig
  name: dig-controller
spec:
  replicas: 1
  selector:
    name: dig
  template:
    metadata:
      labels:
        name: dig
    spec:
      containers:
      - image: ybga/djinn
        command: ['/bin/sh', '-c']
        args: ['cd ../dig/ && ./DIGServer']
        name: dig
        ports:
        - containerPort: 8087
          name: thrift
