apiVersion: v1
kind: Service
metadata:
  name: ensemble
  labels:
    name: ensemble
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    name: ensemble
