apiVersion: v1
kind: Service
metadata:
  name: enwiki
  labels:
    name: enwiki
spec:
  type: LoadBalancer
  ports:
    - port: 8983
      targetPort: 8983
      protocol: TCP
  selector:
    name: enwiki
