apiVersion: v1
kind: Service
metadata:
  name: face
  labels:
    name: face
spec:
  type: LoadBalancer
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
  selector:
    name: face
