apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: face
  name: face-controller
spec:
  replicas: 1
  selector:
    name: face
  template:
    metadata:
      labels:
        name: face
    spec:
      containers:
      - image: ybga/djinn
        command: ['/bin/sh', '-c']
        args: ['cd ../face/ && ./FACEServer']
        name: face
        ports:
        - containerPort: 8086
          name: thrift
