apiVersion: v1
kind: Service
metadata:
  name: freebase
  labels:
    name: freebase
spec:
  type: LoadBalancer
  ports:
    - port: 3030
      targetPort: 3030
      protocol: TCP
  selector:
    name: freebase
