apiVersion: v1
kind: Service
metadata:
  name: label2
  labels:
    name: label2
spec:
  type: LoadBalancer
  ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
  selector:
    name: label2
