apiVersion: v1
kind: Service
metadata:
  name: label1
  labels:
    name: label1
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    name: label1
