apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - mountPath: /data/db
            name: mongo-persistent-storage
            readOnly: false
      volumes:
        - hostPath:
            path: /tmp/mongo
          name: mongo-persistent-storage
