apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: gcr.io/kuberlucida/lucida:20160603_7
        command: ['/bin/sh', '-c']
        args: ['cd commandcenter/ && python app.py']
        name: web
        ports:
        - containerPort: 3000
          name: http-server