apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: ybga/lucida-dev
        command: ['/bin/sh', '-c']
        args: ['export DOCKER=True && cd commandcenter/ && python app.py']
        name: web
        ports:
        - containerPort: 3000
          name: http-server
