apiVersion: v1
kind: Service
metadata:
  name: yodaoffline
  labels:
    name: yodaoffline
spec:
  type: LoadBalancer
  ports:
    - port: 4567
      targetPort: 4567
      protocol: TCP
  selector:
    name: yodaoffline
